version: "3.7"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=app_db
      - MYSQL_PASSWORD=app_password
      - MYSQL_DB=app_db
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_db
      - MYSQL_PASSWORD=app_password
    cap_add:
      - SYS_NICE